apiVersion: v1
kind: Service
metadata:
  name: {{ include "swe-api.fullname" . }}
  labels:
    {{- include "swe-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  selector:
    {{- include "swe-api.selectorLabels" . | nindent 4 }}
